Listen 6066

<VirtualHost *:6066>

    ServerSignature Off

    DocumentRoot /opt/loxberry/webfrontend/html/plugins/weather4lox/emu
    
    <Directory />
            Options Indexes FollowSymLinks MultiViews
            AllowOverride All
            Order allow,deny
            allow from all
    </Directory>

    <Directory /opt/loxberry/webfrontend/html/plugins/weather4lox/emu>
            Options ExecCGI Indexes FollowSymLinks MultiViews
            AddHandler cgi-script cgi
            AllowOverride All
            Order allow,deny
            allow from all
    </Directory>

</VirtualHost>
